version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    command: '--default-authentication-plugin=mysql_native_password --pid-file /var/lib/mysql/mysqld.pid --sql_mode='
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    expose:
      - "3306:3306"
  wordpress:
    image: wordpress:5-fpm-alpine
    #command: bash -c 
    #  - mkdir -p /var/www/html/wp-content/plugins
    #  - mkdir -p /var/www/html/wp-content/uploads
    #  - chown -R www-data:www-data /var/www
    #  - find /var/www/ -type d -exec chmod 0755 {} \;
    #  - find /var/www/ -type f -exec chmod 644 {} \;
    depends_on:
      - db
    container_name: wordpress
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL="letsencrypt@${VIRTUAL_HOST}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf/:/etc/nginx/conf.d
      - ./cert/:/etc/ssl
volumes:
  wordpress:
  dbdata:
