version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    command: '--default-authentication-plugin=mysql_native_password --pid-file /var/lib/mysql/mysqld.pid --sql_mode='
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql

  wordpress:
    restart: always
    container_name: wordpress
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - "8000:80"
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
volumes:
  wordpress:
  dbdata:
